### ISSUE TITLE
No fclose

### ISSUE THREAD

**Issue by pecnik** [prewk/XmlStreamer#13]
return isset($this->rootNode);
fclose($this->handle);

The file is never closed, you return before you close teh file

**Comment by prewk** [comment]
Wow, I can't believe anyone else have seen it for such a long time :)

Thanks, I'll look into it. You should check out https://github.com/prewk/xml-string-streamer/ instead, btw, this lib is deprecated.

**Comment by prewk** [comment]
Fixed in `0.5.0`, bumped the minor version to give people a chance to avoid errors. They should try the newer package `xml-string-streamer` instead, though.
